---
title: "Gov 50 Final Project"
author: "Ebony McDonald"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

I am interested in exploring data related to... voter turnout?

```{r}
library(haven)
data <- read_sav("Data/W110_Jun22/ATP W110.sav")
```



I am interested in understanding how Black Americans evaluate the democratic party, and what drives their statistical continuous support. Specifically, I speculate that Black support for the democratic party may be more based in moral evaluations rather than policy evaluations when compared to white Americans. I believe this is because the democratic party is often understood as having earned Black support due to policies favoring racial justice. I speculate that because as racism is often understood as a moral issues as opposed to a policy issue, black democrats are more likely to associate the democratic party with strong moral standing when compared to white democrats. The Pew Research Center data set that I am working with contains survey questions that prompt respondents to evaluate each party in terms of their capability in handling certain political issues, as well as their moral standing. I hypothesize that the data will demonstrate that black and white democrats will evaluate the democratic party similarly in terms of their capability of managing different policy issues, but that black democrats may be more likely to give the democratic party higher morality rankings. In this case, my explanatory variable is the respondents racial identity (which is offered by the dataset), and my outcome variable is their responses to the types of questions described above. My hypothesis could be disproven if, on average, white respondents gave the democratic party morality ratings similar to or higher than black respondents.